#!/bin/bash

export CONFIG_DIR="$HOME/.config/sketchybar"
export PLUGIN_DIR="$CONFIG_DIR/plugins"
export ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"

# ========================================
# TOP BAR CONFIGURATION
# ========================================
source "$CONFIG_DIR/bar.sh"
source "$ITEM_DIR/spaces2.sh"

${BAR_NAME:-sketchybar} --update
