#!/bin/bash

# power distribution widget, top center of the screen
export PATH="$HOME/.local/bin:$PATH"
export BAR_NAME=powerbar
export CONFIG_DIR="$HOME/.config/sketchybar"
export PLUGIN_DIR="$CONFIG_DIR/plugins"

source "$CONFIG_DIR/colors.sh"

powerbar --bar \
  position=top \
  height=37 \
  margin=0 \
  y_offset=12 \
  corner_radius=32 \
  blur_radius=0 \
  color="$BAR_COLOR"

source "$CONFIG_DIR/defaults.sh"

powerbar --add item power center \
  --subscribe power system_woke power_source_change \
  --set power \
    update_freq=3 \
    icon.drawing=off \
    label.padding_left=8 \
    label.padding_right=8 \
    label.font="Hack Nerd Font:Bold:12.0" \
    background.drawing=on \
    background.color="$ACCENT_COLOR" \
    background.corner_radius=5 \
    background.height=25 \
    icon.color="$WHITE" \
    label.color="$WHITE" \
    script="$PLUGIN_DIR/power.sh"

powerbar --update
