# TTS experimentation by Rohin
# GCloud Text-to-Speech API

text = 'This text was generated by Rohins google cloud api test thingy'
lang = 'en-UK'
gender = 'MALE'

from google.cloud import texttospeech
client = texttospeech.TextToSpeechClient()
synthesis_input = texttospeech.SynthesisInput(text=text)

voice = texttospeech.VoiceSelectionParams(
  language_code=lang, 
  ssml_gender=texttospeech.SsmlVoiceGender[gender]
)

audio_config = texttospeech.AudioConfig( audio_encoding=texttospeech.AudioEncoding.MP3 )
response = client.synthesize_speech( input=synthesis_input, voice=voice, audio_config=audio_config )

with open("output.mp3", "wb") as out:
  out.write(response.audio_content)
  print('Audio content written to file "output.mp3"')